//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_MonthlyExpenses
    {
        public int idMExp { get; set; }
        public string Exp_Name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
