//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id_bill { get; set; }
        public string pro_name { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public int quality { get; set; }
        public Nullable<decimal> tot_price { get; set; }
        public int store { get; set; }
        public Nullable<int> IDproduct { get; set; }
    
        public virtual product product { get; set; }
    }
}
