//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloseDAy
    {
        public int id { get; set; }
        public string processT { get; set; }
        public Nullable<decimal> price { get; set; }
        public string reason { get; set; }
        public string proName { get; set; }
        public Nullable<int> quantity { get; set; }
        public string ReasonOfT { get; set; }
        public string personT { get; set; }
        public string userN { get; set; }
        public System.DateTime DTime { get; set; }
        public int userId { get; set; }
        public int shiftNumber { get; set; }
        public string whoPerson_add { get; set; }
    }
}
