//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloseShift
    {
        public int id { get; set; }
        public string processT { get; set; }
        public Nullable<decimal> price { get; set; }
        public string reason { get; set; }
        public string proName { get; set; }
        public Nullable<int> quantity { get; set; }
        public string ReasonOfTake { get; set; }
        public string personTake { get; set; }
        public string userName { get; set; }
        public System.DateTime dateT { get; set; }
        public int userID { get; set; }
        public int shiftNu { get; set; }
        public string whoPersonAdd { get; set; }
    }
}
