//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.product_process = new HashSet<product_process>();
            this.safes = new HashSet<safe>();
            this.Timings = new HashSet<Timing>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string time_work { get; set; }
    
        public virtual ICollection<product_process> product_process { get; set; }
        public virtual ICollection<safe> safes { get; set; }
        public virtual ICollection<Timing> Timings { get; set; }
    }
}
