//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cornerEntitiesDB : DbContext
    {
        public cornerEntitiesDB()
            : base("name=cornerEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<All_MonthlyExpenses> All_MonthlyExpenses { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<CloseDAy> CloseDAys { get; set; }
        public virtual DbSet<CloseShift> CloseShifts { get; set; }
        public virtual DbSet<Day_Details> Day_Details { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<M_Expenses> M_Expenses { get; set; }
        public virtual DbSet<Month_Details> Month_Details { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_process> product_process { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<safe> safes { get; set; }
        public virtual DbSet<Shift_Details> Shift_Details { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Timing> Timings { get; set; }
        public virtual DbSet<User_shift> User_shift { get; set; }
    }
}
