//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month_Details
    {
        public int id_Month { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public Nullable<decimal> TotalSell { get; set; }
        public Nullable<decimal> TotalBuy { get; set; }
        public Nullable<decimal> profitMonth { get; set; }
        public Nullable<decimal> TotalMonthlyExpenses { get; set; }
    }
}
