//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_process
    {
        public int id_proccess { get; set; }
        public string user_Name { get; set; }
        public string process_type { get; set; }
        public string product_name { get; set; }
        public Nullable<int> quantities { get; set; }
        public Nullable<decimal> price { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<int> IDproduct { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual product product { get; set; }
    }
}
