//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.Bills = new HashSet<Bill>();
            this.product_process = new HashSet<product_process>();
        }
    
        public int product_id { get; set; }
        public string product_Name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> productType_id { get; set; }
        public int store { get; set; }
        public string MakeAButton { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<product_process> product_process { get; set; }
        public virtual product_type product_type { get; set; }
    }
}
