//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class safe
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<decimal> price { get; set; }
        public string reason { get; set; }
        public string product_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string ReasonOfTake { get; set; }
        public string personTake { get; set; }
        public string user_name { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<int> userID { get; set; }
        public string who_PersonAdd { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
