//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corner_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timing
    {
        public string user_Name { get; set; }
        public System.DateTime Login_date_time { get; set; }
        public System.DateTime Logout_date_time { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
