using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Win32;
using Corner_Application; // shared Db (data-folder path)

namespace CornerPos.Licensing
{
    /// <summary>Outcome of a license evaluation at startup.</summary>
    public enum LicenseState { Trial, Licensed, Expired }

    /// <summary>Snapshot of the current licensing situation.</summary>
    public sealed class LicenseStatus
    {
        public LicenseState State { get; set; }
        /// <summary>Whole days remaining (trial days left, or days until the key expires).</summary>
        public int DaysLeft { get; set; }
        /// <summary>Expiry date of the active key, when Licensed.</summary>
        public DateTime? Expiry { get; set; }
        /// <summary>Customer name embedded in the key, when Licensed.</summary>
        public string Customer { get; set; }

        /// <summary>True when a usable license/trial is close to running out.</summary>
        public bool WarnSoon =>
            (State == LicenseState.Trial || State == LicenseState.Licensed)
            && DaysLeft <= LicenseManager.WarnThresholdDays;

        public bool CanUseApp => State != LicenseState.Expired;
    }

    /// <summary>
    /// Offline licensing for CornerPos. A license key is a signed token that embeds an
    /// expiry date; the app verifies its ECDSA (P-256) signature against a PUBLIC key
    /// baked in below. Only the separate key-generator tool holds the matching PRIVATE
    /// key, so keys cannot be forged without it.
    ///
    /// Before any key is entered the app runs a 7-day trial. The trial start date is
    /// mirrored to two places (an HKCU registry value and a hidden file in the data
    /// folder) and cross-checked, so deleting just one of them does not reset the trial.
    ///
    /// This is deliberately "basic tier" protection: it deters casual copying, not a
    /// determined attacker. Expiry is checked against the local clock, and wiping BOTH
    /// trial markers still resets the trial.
    /// </summary>
    public static class LicenseManager
    {
        public const int TrialDays = 7;
        public const int WarnThresholdDays = 5;

        // ---- Embedded PUBLIC key (ECDSA P-256), base64 of the 32-byte X and Y ----
        // Generated by the key-generator tool ("dotnet run --project KeyGen -- keygen").
        // Replacing these invalidates every previously issued key.
        private const string PublicKeyX = "o2QTnp3VmvsI81NNW4XmsiohBnVwuH58SMcNIl9IYwk=";
        private const string PublicKeyY = "3GpGY5minJlr9kOlJXVKnLfdqjQxPEEev2ncTX4V6vw=";

        private const string RegistryKeyPath = @"Software\CornerPos";
        private const string RegistryValueName = "Seed";
        private const long TrialMask = 0x5F3759DF5A17C0DEL; // obfuscation only, not secret

        private static string LicenseFile => Path.Combine(Db.DataDirectory, "license.key");
        private static string TrialFile => Path.Combine(Db.DataDirectory, ".trialstate");

        /// <summary>
        /// Decide the current licensing state. Called once at startup and again after
        /// a key is entered. Never throws — any failure degrades to the trial path.
        /// </summary>
        public static LicenseStatus Evaluate()
        {
            // 1) An entered key wins (whether still valid, or now expired).
            string keyText = TryReadLicenseFile();
            if (!string.IsNullOrWhiteSpace(keyText))
            {
                LicenseKey key;
                if (LicenseKey.TryParseAndVerify(keyText, PublicKeyX, PublicKeyY, out key))
                {
                    int days = (int)Math.Ceiling((key.Expiry.Date - Today).TotalDays);
                    if (key.Expiry.Date >= Today)
                        return new LicenseStatus
                        {
                            State = LicenseState.Licensed,
                            DaysLeft = Math.Max(days, 0),
                            Expiry = key.Expiry,
                            Customer = key.Customer
                        };
                    // A real, but expired, key -> locked out (data is untouched).
                    return new LicenseStatus { State = LicenseState.Expired, Expiry = key.Expiry, Customer = key.Customer };
                }
                // Unverifiable/garbage key file -> ignore and fall through to trial.
            }

            // 2) No usable key: run/continue the trial.
            DateTime start = ReadOrStartTrial();
            int used = (int)Math.Floor((Today - start.Date).TotalDays);
            int left = TrialDays - used;
            if (left > 0)
                return new LicenseStatus { State = LicenseState.Trial, DaysLeft = left };

            return new LicenseStatus { State = LicenseState.Expired };
        }

        /// <summary>
        /// Validate a key the user typed/pasted and, if it is genuine and not expired,
        /// persist it. Returns true on success; otherwise <paramref name="error"/>
        /// carries an Arabic message describing why it was rejected.
        /// </summary>
        public static bool TryActivate(string keyText, out string error)
        {
            error = null;
            keyText = (keyText ?? "").Trim();
            if (keyText.Length == 0) { error = "من فضلك أدخل مفتاح الترخيص."; return false; }

            LicenseKey key;
            if (!LicenseKey.TryParseAndVerify(keyText, PublicKeyX, PublicKeyY, out key))
            {
                error = "مفتاح الترخيص غير صالح.";
                return false;
            }
            if (key.Expiry.Date < Today)
            {
                error = "انتهت صلاحية هذا المفتاح بتاريخ " + key.Expiry.ToString("yyyy-MM-dd") + ".";
                return false;
            }

            try
            {
                Directory.CreateDirectory(Db.DataDirectory);
                File.WriteAllText(LicenseFile, keyText, Encoding.UTF8);
                return true;
            }
            catch (Exception ex)
            {
                error = "تعذر حفظ المفتاح: " + ex.Message;
                return false;
            }
        }

        private static DateTime Today => DateTime.UtcNow.Date;

        private static string TryReadLicenseFile()
        {
            try { return File.Exists(LicenseFile) ? File.ReadAllText(LicenseFile, Encoding.UTF8) : null; }
            catch { return null; }
        }

        // ---- Trial marker: mirrored across registry + hidden file, cross-checked ----

        private static DateTime ReadOrStartTrial()
        {
            DateTime? fromReg = ReadRegistryStart();
            DateTime? fromFile = ReadFileStart();

            // Earliest known start wins, so recreating one marker at "now" cannot shorten
            // (or reset) a trial while the other marker still remembers the real start.
            DateTime? start = null;
            if (fromReg.HasValue) start = fromReg;
            if (fromFile.HasValue && (!start.HasValue || fromFile.Value < start.Value)) start = fromFile;

            if (!start.HasValue) start = DateTime.UtcNow; // genuine first run

            // Re-mirror to heal a missing/tampered side.
            WriteRegistryStart(start.Value);
            WriteFileStart(start.Value);
            return start.Value;
        }

        private static DateTime? ReadRegistryStart()
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.OpenSubKey(RegistryKeyPath))
                {
                    if (k == null) return null;
                    return DecodeTicks(k.GetValue(RegistryValueName) as string);
                }
            }
            catch { return null; }
        }

        private static void WriteRegistryStart(DateTime start)
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.CreateSubKey(RegistryKeyPath))
                    if (k != null) k.SetValue(RegistryValueName, EncodeTicks(start), RegistryValueKind.String);
            }
            catch { /* best effort */ }
        }

        private static DateTime? ReadFileStart()
        {
            try { return File.Exists(TrialFile) ? DecodeTicks(File.ReadAllText(TrialFile)) : null; }
            catch { return null; }
        }

        private static void WriteFileStart(DateTime start)
        {
            try
            {
                Directory.CreateDirectory(Db.DataDirectory);
                File.WriteAllText(TrialFile, EncodeTicks(start));
                File.SetAttributes(TrialFile, FileAttributes.Hidden);
            }
            catch { /* best effort */ }
        }

        private static string EncodeTicks(DateTime dt)
        {
            long v = dt.ToUniversalTime().Ticks ^ TrialMask;
            return Convert.ToBase64String(BitConverter.GetBytes(v));
        }

        private static DateTime? DecodeTicks(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return null;
            try
            {
                long v = BitConverter.ToInt64(Convert.FromBase64String(s), 0) ^ TrialMask;
                return new DateTime(v, DateTimeKind.Utc);
            }
            catch { return null; }
        }
    }

    /// <summary>
    /// A parsed license token: <c>base64url(payload).base64url(signature)</c> where the
    /// payload is UTF-8 text <c>v1|yyyyMMdd|customer</c>. The signature is ECDSA/SHA-256
    /// over the payload bytes, in IEEE-P1363 format (the platform default on both the
    /// generator and here), verifiable against the embedded public key.
    /// </summary>
    public sealed class LicenseKey
    {
        public DateTime Expiry { get; private set; }
        public string Customer { get; private set; }

        public static bool TryParseAndVerify(string token, string pubX, string pubY, out LicenseKey key)
        {
            key = null;
            if (string.IsNullOrWhiteSpace(token)) return false;

            int dot = token.IndexOf('.');
            if (dot <= 0 || dot >= token.Length - 1) return false;

            byte[] payload, sig;
            try
            {
                payload = FromBase64Url(token.Substring(0, dot));
                sig = FromBase64Url(token.Substring(dot + 1));
            }
            catch { return false; }

            if (!VerifySignature(payload, sig, pubX, pubY)) return false;

            string text = Encoding.UTF8.GetString(payload);
            string[] parts = text.Split(new[] { '|' }, 3);
            if (parts.Length < 2 || parts[0] != "v1") return false;

            DateTime expiry;
            if (!DateTime.TryParseExact(parts[1], "yyyyMMdd",
                    System.Globalization.CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None, out expiry))
                return false;

            key = new LicenseKey
            {
                Expiry = DateTime.SpecifyKind(expiry, DateTimeKind.Utc),
                Customer = parts.Length >= 3 ? parts[2] : ""
            };
            return true;
        }

        private static bool VerifySignature(byte[] payload, byte[] sig, string pubX, string pubY)
        {
            try
            {
                var p = new ECParameters
                {
                    Curve = ECCurve.NamedCurves.nistP256,
                    Q = new ECPoint
                    {
                        X = Convert.FromBase64String(pubX),
                        Y = Convert.FromBase64String(pubY)
                    }
                };
                using (var ecdsa = ECDsa.Create())
                {
                    ecdsa.ImportParameters(p);
                    return ecdsa.VerifyData(payload, sig, HashAlgorithmName.SHA256);
                }
            }
            catch { return false; }
        }

        private static byte[] FromBase64Url(string s)
        {
            string b = s.Replace('-', '+').Replace('_', '/');
            switch (b.Length % 4) { case 2: b += "=="; break; case 3: b += "="; break; }
            return Convert.FromBase64String(b);
        }
    }
}
